#!/bin/sh
TERM=kitty

[ ! -e "$HOME/.local/share/packageDB" ] && paru -Slq > "$HOME/.local/share/packageDB"

result=$(cat "$HOME/.local/share/packageDB" | bemenu -l 10 -p "Install Package: ")

[ -n "$result" ] && $TERM -e paru -S "$result"
